language: c

services:
        - docker

before_install:
        - docker build -t idodin/functional:latest .

deploy:
        provider: script
        script: bash docker_push
        on:
                branch: master
