language: c

services:
        - docker

script:
        - docker build -t compete-mcgill/functional:latest .

deploy:
        provider: script
        script: bash docker_push
        on:
                branch: master
